# 답안 작성 방법

아래 이미지에서 "더블클릭 또는 Enter키를 눌러 수정"을 누르신후 해당 창에 답을 적으시면 됩니다.

![image](https://github.com/user-attachments/assets/2aa2ff05-fb0e-4f00-a121-78afeaad4f09)

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

# 07차시 과제

### Q1. 길이가 5인 1차원 텐서를 만들어 보세요. 이 텐서의 모든 원소는 1로 초기화되어야 합니다.

In [1]:
import torch

tensor_1d= torch.ones(5)
print(tensor_1d)

tensor([1., 1., 1., 1., 1.])


### Q2. 3x3 크기의 2차원 텐서를 생성하고, 모든 원소를 0으로 초기화하세요.

In [2]:
import torch

tensor_2d = torch.zeros(3, 3)
print(tensor_2d)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


### Q3. 두 개의 텐서 a와 b를 만들어 각각 2x2 크기로 초기화하고, 이 두 텐서를 더해보세요

In [4]:
import torch

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

result = a + b
print(result)

tensor([[ 6,  8],
        [10, 12]])


### Q4. 다음은 PyTorch를 사용하여 자동 미분을 수행하려는 코드이다. 그러나 코드에는 오류가 있다. 해당 오류를 수정하여 올바르게 자동 미분을 수행하라.


In [12]:
import torch

x = torch.tensor([1, 2, 3], requires_grad=True ,dtype=torch.float64)
y = torch.tensor([4, 5, 6])

z = torch.sum(x * y)

loss = z

loss.backward()
x.grad

tensor([4., 5., 6.], dtype=torch.float64)

x에 requires_grad=True를 활성화 해줘야 하고, 데이터 타입을 float으로 변경해야합니다.


### Q5. torch의 zero_grad 함수는 무엇이며, 어떠한 역할을 하는가? 그리고 만약 zero_grad를 호출하지 않으면 어떤 문제가 발생하는가?

 zero_grad: 이전 기울기를 0으로 초기화합니다. 자동 미분을 사용 할때 backward 호출될 때 마다 값에 더해집니다.

 호출하지 않으면 이전단계의 기울기가 계속 새로운 기울기에 더해지며 영향을 줘 올바른 기울기 계산이 어렵습니다.


### Q6. torch의 MSE함수를 이용하여 제공된 두 텐서(A, B)의 mean square error를 구하시오.

In [26]:
import torch

A = torch.tensor([[1, 2], [3, 4]],dtype=torch.float64)
B = torch.tensor([[5, 6], [7, 8]],dtype=torch.float64)

# MSE Loss

loss = torch.nn.MSELoss()(A, B)



# Write your code here
print(loss)


tensor(16., dtype=torch.float64)


### Q7.  K-means 클러스터링이 무엇이고, 각 알고리즘의 주요 단계들을 설명하라.

1. 초기화: k개의 중심을 임의 선택
2. 할당: 데이터 포인트를 가장 가까운 중심에 할당
3. 중심 업데이트: 군집의 중심을 할당된 데이터 포인트의 평균을 갱신
4. 반복: 수렴할때까지 할당, 업데이트 반복
